service: pager-duty-sync

provider:
  name: aws
  runtime: python3.8
  stage: ${env:AWS_STAGE}
  region:  ${env:AWS_REGION}
  profile: ${env:AWS_DEPLOY_PROFILE}

functions:
  exportToS3:
    handler: functions.export_pager_duty_reports_to_s3
    events:
     #- http: POST /sync/s3
      - 
        schedule: 
          enabled: true
          rate: cron(0 0 * * ? *)

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-dotenv-plugin
  - serverless-python-requirements
  
package:
  exclude:
    - node_modules/**
    - node_modules
    - .env

custom:
  s3:
    port: ${env:LOCAL_S3_PORT}
    directory: ${env:LOCAL_S3_DIR}
  

  # Add custom dotenv includes
  dotenv:
    logging: false
    include:
      # Include S3 creds for bucket
      - AWS_S3_USER_SECRET
      - AWS_S3_USER_ACCESS_KEY_ID
      - AWS_S3_BUCKET_NAME
      - AWS_S3_USER_REGION
      
      # Include pagerduty creds
      - PAGER_DUTY_API_TOKEN
      - PAGER_DUTY_SCHEDULE_ID
  
  pythonRequirements:
    dockerizePip: true

resources:
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${env:AWS_S3_BUCKET_NAME}